"""
AI LAB GUI — FastAPI Backend

Architecture contract:
- Thin API layer ONLY — zero decision logic
- All execution flows through orchestrator_runtime.execute_from_input
- All control flows through user_control and background_manager
- All approval flows through user_approval
- MUST NOT call main.py
- MUST NOT modify orchestrator or alter workflow
"""

import os
import sys

# Resolve project root (2 levels up from backend/)
# ROOT = directory that contains the "system/" folder
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# Set working directory so all relative paths inside the system resolve correctly
os.chdir(ROOT)

# Ensure package imports work from any launch location
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Any, Optional
import asyncio
import threading
import uuid as _uuid_mod
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone

# === SYSTEM IMPORTS (verified real contracts) ===
from system.orchestrator.orchestrator_runtime import execute_from_input, get_workflow_id_for_thread, run_workflow
from system.orchestrator.user_control import (
    get_control_state,
)
from system.orchestrator.workflow_control import (
    pause_workflow,
    resume_workflow,
    get_plan,
    edit_step,
    add_step as add_plan_step,
    remove_step as remove_plan_step,
    reorder_steps,
    retry_step,
    stop_workflow,
    cancel_workflow,
    _get_workflow_state,
    warm_registry_from_disk,
    validate_runtime_activation,
)
from system.orchestrator.persistence import workflow_persistence_exists as _wf_persistence_exists, load_active_workflows
from system.orchestrator.bootstrap import initialize_system
from system.runtime.background_manager import BackgroundManager

# === CANONICAL PROJECTION TRANSPORT (Phase 4A.0) ===
# Per CANONICAL_PROJECTION_MODEL_V1: API is transport-only — does NOT own projection truth
# Per ORCHESTRATOR_CONTRACT_V2: API transports projections generated by Orchestrator Runtime
# FAILURE-ISOLATED: Import failure must not affect other API functionality
try:
    from system.orchestrator.projection_manager import get_projection_manager as _get_proj_mgr
    from system.orchestrator.projection_schema import validate_projection_identity
except Exception:
    _get_proj_mgr = None
    validate_projection_identity = None

# === BG_ID CONTINUITY PERSISTENCE (Phase 3F-XA) ===
# Per LIFECYCLE_AND_PROJECTION_AUTHORITY_CONTRACT_V1 §RESUME RULES:
# Resume MUST reuse same projection identity (bg_id) to maintain continuity.
# bg_id_map persists bg_id → orchestrator_workflow_id mapping across restarts.
# FAILURE-ISOLATED: Import failure must not affect other API functionality.
try:
    from system.orchestrator.bg_id_map import (
        register_bg_id as _register_bg_id,
        deregister_bg_id as _deregister_bg_id,
        load_all as _load_bg_id_map,
    )
except Exception:
    _register_bg_id = None
    _deregister_bg_id = None
    _load_bg_id_map = None

# === PLAN MUTATION MANAGER (Phase 4B.1) ===
# Per CANONICAL_PROJECTION_MODEL_V1 §7: API routes mutation intents only
# API MUST NOT own mutation authority
# FAILURE-ISOLATED: Import failure must not affect other API functionality
try:
    from system.orchestrator.plan_mutation_manager import request_plan_mutation as _request_plan_mutation
    from system.orchestrator.mutation_validation import ALLOWED_MUTATION_TYPES as _ALLOWED_MUTATION_TYPES
except Exception:
    _request_plan_mutation = None
    _ALLOWED_MUTATION_TYPES = frozenset()

# ── module-level singletons ──────────────────────────────────────────────────
_bg_manager = BackgroundManager()
_executor = ThreadPoolExecutor(max_workers=4)

# ── pending approvals queue (GUI-facing approval flow) ──────────────────────
# Maps step_id → {"step": dict, "resolve": asyncio.Future}
_pending_approvals: dict[str, dict] = {}


# ── PROJECTION LAYER (Contract-Compliant Data Model) ──────────────────────
# Per GUI_ARCHITECTURE.txt: outputs should be separate from steps
# Per PLAN_STEP_CONTRACT_V1: plan steps MUST NOT include tool_call
def project_workflow_for_gui(workflow: dict) -> dict:
    """
    Project workflow data to contract-compliant GUI model.
    
    Transforms internal workflow representation (with execution_result and tool_call
    attached to steps) into external GUI representation (steps without execution fields,
    outputs in separate structure).
    
    Args:
        workflow: Internal workflow dict with steps containing execution_result and tool_call
        
    Returns:
        Contract-compliant dict with:
        - steps: Plan step fields only (no execution_result, no tool_call)
        - outputs: Separate array of execution results
        - workflow_output: Top-level workflow output
    """
    if not workflow or not isinstance(workflow, dict):
        return workflow
    
    # Extract outputs and clean steps
    outputs = []
    cleaned_steps = []
    
    for step in workflow.get("steps", []):
        if not isinstance(step, dict):
            cleaned_steps.append(step)
            continue
        
        # Extract execution_result if present
        execution_result = step.get("execution_result")
        if execution_result:
            outputs.append({
                "step_id": step.get("id"),
                "execution_result": execution_result
            })
        
        # Clean step - remove execution-only fields
        cleaned_step = {
            "id": step.get("id"),
            "type": step.get("type"),
            "purpose": step.get("purpose"),
            "expected_outcome": step.get("expected_outcome"),
            "risk": step.get("risk"),
            "importance": step.get("importance"),
            "depends_on": step.get("depends_on"),
            "resource_targets": step.get("resource_targets"),
            "status": step.get("status"),
            "retries": step.get("retries", 0)
        }
        
        # === SEMANTIC GATE (Phase 4G-A.9): blocked_reason is ONLY valid on BLOCKED steps ===
        # Per DEPENDENCY_MODEL_CONTRACT_V1: blocked_reason must not appear on non-BLOCKED steps.
        if step.get("status") == "BLOCKED" and step.get("blocked_reason"):
            cleaned_step["blocked_reason"] = step["blocked_reason"]
        
        cleaned_steps.append(cleaned_step)
    
    # Return contract-compliant structure
    return {
        "steps": cleaned_steps,
        "outputs": outputs,
        "workflow_output": workflow.get("output")
    }


def project_step_for_approval(step: dict) -> dict:
    """
    Project step data for approval panel.
    
    Removes execution-only fields (tool_call, execution_result) while keeping
    plan step fields needed for approval decision.
    
    Args:
        step: Internal step dict
        
    Returns:
        Contract-compliant step dict without execution fields
    """
    if not step or not isinstance(step, dict):
        return step
    
    return {
        "id": step.get("id"),
        "type": step.get("type"),
        "purpose": step.get("purpose"),
        "expected_outcome": step.get("expected_outcome"),
        "risk": step.get("risk"),
        "importance": step.get("importance"),
        "status": step.get("status")
    }

app = FastAPI(title="AI Lab GUI API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def _evict_workflow_state(workflow_id: str, bg_id: str = None, reason: str = "") -> None:
    """
    Single authoritative cleanup path — replaces _evict_orphaned_runtime_state
    and _cleanup_partial_execution_state.

    Called from:
      - startup eviction (invalid/quarantined workflows)
      - stream_active / stream_workflow_id (no persistence found)
      - execution failure rollback

    Responsibilities (all idempotent):
      1. Remove bg_id entry from _stream_registry
      2. Remove bg_id → workflow_id mapping from bg_id_map persistence
      3. Evict workflow projection from projection store
      4. Mark runtime registry as FAILED

    Failure MUST NOT affect startup or other workflows.
    """
    print(f"[EVICT] workflow={workflow_id} bg={bg_id} reason={reason}")

    # 1. Remove from in-memory stream registry
    if bg_id:
        try:
            with _stream_registry_lock:
                _stream_registry.pop(bg_id, None)
        except Exception:
            pass

    # 2. Deregister from bg_id_map persistence
    if bg_id:
        try:
            if _deregister_bg_id is not None:
                _deregister_bg_id(bg_id)
        except Exception:
            pass

    # 3. Evict projection store entry
    if workflow_id:
        try:
            if _get_proj_mgr is not None:
                _pm = _get_proj_mgr()
                _pm.remove_workflow(workflow_id)
        except Exception:
            pass

    # 4. Mark registry FAILED — do NOT touch persistence
    if workflow_id:
        try:
            from system.orchestrator.workflow_control import _update_runtime_registry_only as _urro_evict
            _urro_evict(workflow_id, "FAILED", f"evicted:{reason}")
        except Exception:
            pass


@app.on_event("startup")
def on_startup():
    """
    Per PHASE 1 REMEDIATION:
    - PERSISTENCE-DRIVEN RECOVERY ONLY
    - Runtime metadata is DERIVED, never authoritative
    - NO resurrection from stream registry or bg_id_map
    - Persistence files are the ONLY resurrection authority

    New startup ordering:
    Phase A: load_active_workflows() — ONLY resurrection authority
    Phase B: validate persisted workflows
    Phase C: resurrect eligible workflows
    Phase D: rebuild runtime metadata (bg_id_map, stream registry, projections)
    """
    initialize_system()

    # === PHASE A: Load persistence files (ONLY resurrection authority) ===
    print("[RECOVERY:PERSISTENCE_LOAD] Loading persisted workflows")
    try:
        _all_disk_wfs = load_active_workflows()
        print(f"[RECOVERY:PERSISTENCE_LOAD] Loaded {len(_all_disk_wfs)} persisted workflows")
    except Exception as _e:
        print(f"[RECOVERY:PERSISTENCE_LOAD] Failed (non-fatal): {_e}")
        _all_disk_wfs = []

    # === Registry warm restoration (normalizes ACTIVE → PENDING_RECOVERY) ===
    try:
        _warm_result = warm_registry_from_disk()
        print(
            f"[STARTUP] Registry warm restore: {_warm_result['restored']} restored, "
            f"{_warm_result['normalized_active']} ACTIVE\u2192PENDING_RECOVERY, "
            f"{_warm_result['skipped']} skipped"
        )
    except Exception as _e:
        print(f"[STARTUP] Registry warm restore failed (non-fatal): {_e}")

    # === PHASE B: Validate persisted workflows ===
    print("[RECOVERY:VALIDATED] Validating persisted workflows")
    from system.orchestrator.workflow_control import (
        validate_workflow_recovery as _vwr,
        quarantine_workflow as _qwf,
        _update_runtime_registry_only as _urro,
    )

    _eligible_workflows = []  # (workflow_id, workflow_dict)
    _cnt = {"eligible": 0, "skip_terminal": 0, "quarantine": 0, "error": 0}

    for _wf in _all_disk_wfs:
        _wf_id = _wf.get("id")
        if not _wf_id:
            continue

        try:
            _vr = _vwr(_wf)

            if _vr["skip"]:
                _cnt["skip_terminal"] += 1
                print(f"[RECOVERY:VALIDATED] SKIP    wf={_wf_id} reason={_vr['reason']}")
                continue

            if _vr["quarantine"]:
                _qwf(_wf, _vr["reason"])
                _cnt["quarantine"] += 1
                print(f"[RECOVERY:VALIDATED] QUARANTINE wf={_wf_id} reason={_vr['reason']}")
                continue

            # ELIGIBLE for resurrection
            _eligible_workflows.append((_wf_id, _wf))
            _cnt["eligible"] += 1
            print(f"[RECOVERY:VALIDATED] ELIGIBLE wf={_wf_id}")

        except Exception as _e:
            _cnt["error"] += 1
            print(f"[RECOVERY:VALIDATED] ERROR   wf={_wf_id} exception={str(_e)}")

    print(f"[RECOVERY:VALIDATED] Summary: {_cnt['eligible']} eligible, {_cnt['skip_terminal']} terminal, {_cnt['quarantine']} quarantined, {_cnt['error']} errors")

    # === PHASE C: Resurrect eligible workflows ===
    print("[RECOVERY:RESURRECT] Resurrecting eligible workflows")
    _resurrected_count = 0

    for _wf_id, _wf in _eligible_workflows:
        try:
            # Transition registry to ACTIVATING first (PENDING_RECOVERY → ACTIVATING → ACTIVE)
            _urro(_wf_id, "ACTIVATING", "startup_resurrection_bootstrap")
            print(f"[LIFECYCLE] ACTIVATING workflow {_wf_id} for resurrection")

            # Spawn execution thread (will complete ACTIVATING → ACTIVE after bootstrap)
            _spawned_bg = _maybe_resurrect_execution(_wf_id)

            if _spawned_bg is not None:
                _resurrected_count += 1
                print(f"[RECOVERY:RESURRECT] RESURRECTED wf={_wf_id} bg={_spawned_bg}")
            else:
                # Spawn failed — evict to avoid ACTIVATING limbo state
                print(f"[RECOVERY:RESURRECT] SPAWN_FAILED wf={_wf_id} — evicting to prevent ACTIVATING limbo")
                _evict_workflow_state(_wf_id, bg_id=None, reason="startup_spawn_failed")

        except Exception as _e:
            print(f"[RECOVERY:RESURRECT] ERROR   wf={_wf_id} exception={str(_e)}")
            _evict_workflow_state(_wf_id, bg_id=None, reason=f"startup_resurrect_exception:{str(_e)}")

    print(f"[RECOVERY:RESURRECT] Resurrected {_resurrected_count} workflows")

    # === PHASE D: Rebuild runtime metadata (DERIVED ONLY) ===
    print("[RECOVERY:RUNTIME_REBUILD] Rebuilding runtime metadata from resurrected workflows")

    # Stream registry is NOT cleared here. Phase C resurrection populates it with entries
    # for resurrected workflows. Clearing here would destroy that work.
    # Any genuinely stale entries (no matching resurrected workflow) are evicted by the
    # fast _wf_persistence_exists() checks in the /active and /workflow_id endpoints.

    # Reconstruct stream registry from bg_id_map for resurrected workflows.
    # bg_id_map persists bg_id → workflow_id across restarts. For each resurrected
    # workflow, restore its stream registry entry so the frontend can reconnect using
    # the same bg_id it held before the restart.
    try:
        if _load_bg_id_map is not None:
            _persisted_bg_map = _load_bg_id_map()
            _resurrected_ids = {wf_id for wf_id, _ in _eligible_workflows}
            _bg_restored = 0
            for _bg_id_key, _wf_id_val in _persisted_bg_map.items():
                if _wf_id_val not in _resurrected_ids:
                    continue
                with _stream_registry_lock:
                    if _bg_id_key not in _stream_registry:
                        _stream_registry[_bg_id_key] = {
                            "orchestrator_workflow_id": _wf_id_val,
                            "workflow": None,
                            "result": None,
                            "status": "PENDING_RECOVERY",
                            "error": None,
                        }
                        _bg_restored += 1
            print(f"[RECOVERY:RUNTIME_REBUILD] Stream registry: {_bg_restored} entries restored from bg_id_map")
    except Exception as _e:
        print(f"[RECOVERY:RUNTIME_REBUILD] bg_id_map stream restore failed (non-fatal): {_e}")

    # Projection stores are DERIVED - restore them with validation
    try:
        if _get_proj_mgr is not None:
            _proj_mgr = _get_proj_mgr()
            _store_result = _proj_mgr.warm_stores_from_disk(_get_workflow_state)
            print(
                f"[RECOVERY:RUNTIME_REBUILD] Projection stores: {_store_result['restored']} restored, "
                f"{_store_result['skipped_stale']} stale skipped, "
                f"{_store_result['errors']} errors"
            )
    except Exception as _e:
        print(f"[RECOVERY:RUNTIME_REBUILD] Projection store restore failed (non-fatal): {_e}")

    print("[STARTUP] Startup recovery complete")


# =============================================================================
# REQUEST MODELS
# =============================================================================

class ExecuteRequest(BaseModel):
    input: str



class ResumeRequest(BaseModel):
    workflow_id: str


class PauseRequest(BaseModel):
    workflow_id: str


class PlanEditRequest(BaseModel):
    workflow_id: str
    step_id: str
    updates: dict


class PlanAddRequest(BaseModel):
    workflow_id: str
    step_data: dict


class PlanRemoveRequest(BaseModel):
    workflow_id: str
    step_id: str


class PlanReorderRequest(BaseModel):
    workflow_id: str
    new_order: list


class RetryStepRequest(BaseModel):
    workflow_id: str
    step_id: str


class StopWorkflowRequest(BaseModel):
    workflow_id: str


class ApprovalRequest(BaseModel):
    workflow_id: str
    step_id: str
    approved: bool


class MutationRequest(BaseModel):
    mutation_type: str
    payload: dict
    actor: Optional[str] = "user"


class BackgroundStartRequest(BaseModel):
    input: str


# =============================================================================
# PHASE 2.1 — EXECUTION
# =============================================================================

@app.post("/execute")
async def execute(req: ExecuteRequest):
    """
    POST /execute
    Calls orchestrator_runtime.execute_from_input(input).
    Returns contract-compliant projection (steps without execution fields, outputs separate).
    """
    if not req.input or not req.input.strip():
        raise HTTPException(status_code=400, detail="input must not be empty")

    loop = asyncio.get_event_loop()
    result = await loop.run_in_executor(_executor, execute_from_input, req.input)
    
    # Apply projection layer for contract compliance
    if result and isinstance(result, dict) and "steps" in result:
        result = project_workflow_for_gui(result)
    
    return result


# =============================================================================
# PHASE 2.1b — STREAMING EXECUTION (non-blocking, returns workflow_id early)
# =============================================================================

# Per LIFECYCLE_AND_PROJECTION_AUTHORITY_CONTRACT_V1:
# - Runtime registry is sole lifecycle authority
# - Stream registry is PROJECTION CACHE ONLY
# - Stream registry mirrors runtime authority, never originates lifecycle state
# - All lifecycle state must derive from runtime registry via _get_workflow_state()

# Registry: bg_id → {"orchestrator_workflow_id": str|None, "result": dict|None, "status": str}
# Note: "status" field is projection cache, NOT authoritative lifecycle state
_stream_registry: dict = {}
_stream_registry_lock = threading.Lock()


def _run_workflow_wrapper(bg_id: str, workflow_or_input, mode: str = "new") -> None:
    """
    Single unified execution thread wrapper.

    mode="new"         — calls execute_from_input(user_input, bg_id, ...)
    mode="resurrect"   — calls run_workflow(workflow, bg_id, ...)
    mode="resume"      — calls run_workflow(workflow, bg_id, ...)

    After execution: writes result to stream registry, reads authoritative status
    from runtime registry, deregisters bg_id on terminal state.
    """
    try:
        if mode == "new":
            result = execute_from_input(workflow_or_input, bg_id, _stream_registry, _stream_registry_lock)
            orchestrator_wf_id = result.get("workflow_id") or result.get("id")
        else:
            result = run_workflow(
                workflow_or_input, bg_id,
                stream_registry=_stream_registry,
                stream_registry_lock=_stream_registry_lock,
            )
            orchestrator_wf_id = workflow_or_input.get("id") if isinstance(workflow_or_input, dict) else None

        with _stream_registry_lock:
            if bg_id in _stream_registry:
                _stream_registry[bg_id]["result"] = result
                # Per PHASE VI §5: Stream registry consumes ONLY from authority
                runtime_state = _get_workflow_state(orchestrator_wf_id) if orchestrator_wf_id else None
                if runtime_state:
                    _stream_registry[bg_id]["status"] = runtime_state["status"]
                    _stream_registry[bg_id]["runtime_activity"] = runtime_state.get("runtime_activity")
                else:
                    # Phase 4G-A.9: UNKNOWN MUST NOT leak into operator UI.
                    # Use None so frontend renders Pending / no label instead of UNKNOWN.
                    _stream_registry[bg_id]["status"] = None
            else:
                # === PHASE XV-B TRACE LOGGING ===
                print("[STREAM_REGISTER]")
                print(f"  bg_id={bg_id}")
                print(f"  workflow_id={orchestrator_wf_id}")
                print(f"  status={runtime_state['status'] if runtime_state else 'PENDING'}")
                _stream_registry[bg_id] = {
                    "orchestrator_workflow_id": orchestrator_wf_id,
                    "result": result,
                    # Phase 4G-A.9: UNKNOWN MUST NOT leak into operator UI.
                    "status": runtime_state["status"] if runtime_state else None,
                    "runtime_activity": runtime_state.get("runtime_activity") if runtime_state else None,
                    "error": None,
                }

        # === PHASE XII §2: bg_id CLEANUP HARDENING ===
        # Per PHASE XII: deregister bg_id after terminal convergence succeeds.
        # BLOCKED is included because run_workflow exits on BLOCKED — the execution
        # thread is dead and bg_id no longer maps to a live execution context.
        # Resurrection (retry/resume) re-registers a fresh bg_id if needed.
        try:
            _final_status = _stream_registry.get(bg_id, {}).get("status", "")
            if _final_status in ("COMPLETED", "FAILED", "CANCELLED", "BLOCKED") and _deregister_bg_id is not None:
                _deregister_bg_id(bg_id)
            # === PHASE XV-B TRACE LOGGING ===
            print("[STREAM_REMOVE]")
            print(f"  bg_id={bg_id}")
            print(f"  workflow_id={orchestrator_wf_id}")
            print(f"  reason=terminal_status:{_final_status}")
        except Exception:
            pass

    except Exception as e:
        with _stream_registry_lock:
            if bg_id in _stream_registry:
                orchestrator_wf_id = _stream_registry[bg_id].get("orchestrator_workflow_id")
                runtime_state = _get_workflow_state(orchestrator_wf_id) if orchestrator_wf_id else None
                _stream_registry[bg_id]["status"] = runtime_state["status"] if runtime_state else "FAILED"
                _stream_registry[bg_id]["error"] = str(e)


def _maybe_resurrect_execution(workflow_id: str) -> Optional[str]:
    """
    Execution resurrection bridge for retry/edit mutations on terminal workflows.

    Per ORCHESTRATOR_EXECUTION_CONTRACT: run_workflow is the sole execution authority.
    Per LIFECYCLE_AUTHORITY_CONTRACT_V1: _update_workflow_state is the sole lifecycle writer.
    Per PROJECTION_CONTINUITY_CONTRACT_V1: reuse existing bg_id to preserve stream identity.

    When a retry/edit mutation resets a BLOCKED/FAILED workflow back to ACTIVE (via
    retry_step → _update_workflow_state(wf_id, "ACTIVE")), the original execution thread
    is already dead — run_workflow exited when the workflow first hit BLOCKED/FAILED.
    The mutation writes correct state into persistence and registry but no thread is
    consuming it.  This function detects that gap and spawns a new run_workflow thread,
    exactly as /resume/{workflow_id} does, but triggered from the mutation pipeline.

    Returns:
        bg_id if resurrection was triggered, None if not needed (workflow not ACTIVE or
        already has a running thread, or workflow not found in persistence).

    Contract compliance:
    - Does NOT call resume_workflow() — that function checks PAUSED/BLOCKED guard which
      would reject because the mutation already wrote ACTIVE directly.
    - Does NOT write lifecycle state — mutation manager already did that correctly.
    - Does NOT mutate projection — projection was already rebuilt by _invalidate_and_reemit.
    - Only spawns execution thread and updates stream registry projection cache.
    """
    # Check authoritative registry — resurrect for ACTIVE, ACTIVATING, or PENDING_RECOVERY.
    # Startup sets ACTIVATING before calling this function, so ACTIVE-only check always
    # rejected all resurrection. PENDING_RECOVERY is the normalized state after warm_registry.
    _auth = _get_workflow_state(workflow_id)
    if not _auth or _auth.get("status") not in ("ACTIVE", "ACTIVATING", "PENDING_RECOVERY"):
        return None

    # === PHASE-IVB: EXECUTION GENERATION COORDINATION ===
    # Increment workflow_execution_generation for resurrection replacement.
    # This is NON-authoritative coordination metadata only. It does NOT gate lifecycle
    # transitions. Per PHASE-IVA EXECUTION LEASE COORDINATION DESIGN AUDIT.
    try:
        from system.orchestrator.workflow_control import _workflow_state_registry, _workflow_state_lock
        with _workflow_state_lock:
            _current_gen = _workflow_state_registry.get(workflow_id, {}).get("execution_generation", 1)
            _workflow_state_registry[workflow_id]["execution_generation"] = _current_gen + 1
            print(f"[EXECUTION_GENERATION] Resurrection incremented workflow={workflow_id} generation={_current_gen + 1}")
    except Exception as e:
        print(f"[EXECUTION_GENERATION] Failed to increment generation for workflow={workflow_id}: {e}")
        # Non-fatal — proceed with resurrection

    # Fast single-file load — do NOT call load_active_workflows() (full scan).
    from system.orchestrator.persistence import _active_workflow_path as _awp
    import json as _json
    try:
        with open(_awp(workflow_id), "r", encoding="utf-8") as _f:
            workflow = _json.load(_f)
    except Exception:
        return None
    if not isinstance(workflow, dict) or workflow.get("id") != workflow_id:
        return None

    # Sync compatibility mirror from authoritative registry ONLY
    from system.orchestrator.workflow_control import inject_authoritative_lifecycle_into_workflow
    inject_authoritative_lifecycle_into_workflow(workflow)

    print(f"[RESURRECTION] workflow={workflow_id} state={_auth.get('status')}")

    # Find or create bg_id — reuse for projection continuity (in-place update)
    bg_id = None
    with _stream_registry_lock:
        for existing_bg_id, entry in _stream_registry.items():
            if entry.get("orchestrator_workflow_id") == workflow_id:
                bg_id = existing_bg_id
                entry["result"] = None
                entry["error"] = None
                _res_auth = _get_workflow_state(workflow_id)
                entry["status"] = _res_auth["status"] if _res_auth else "ACTIVE"
                entry["workflow"] = None
                break

    if bg_id is None:
        bg_id = str(_uuid_mod.uuid4())
        with _stream_registry_lock:
            _res_auth_new = _get_workflow_state(workflow_id)
            _stream_registry[bg_id] = {
                "orchestrator_workflow_id": workflow_id,
                "workflow": None,
                "result": None,
                "status": _res_auth_new["status"] if _res_auth_new else "ACTIVE",
                "error": None,
            }

    t = threading.Thread(
        target=_run_workflow_wrapper,
        args=(bg_id, workflow),
        kwargs={"mode": "resurrect"},
        daemon=True,
        name=f"resurrect-{bg_id[:8]}",
    )
    t.start()
    return bg_id


@app.post("/execute/stream")
def execute_stream(req: ExecuteRequest):
    """
    POST /execute/stream
    Starts execute_from_input in a background thread.
    Returns bg_id immediately — frontend uses this to poll for workflow_id and result.
    Execution path is identical to /execute — no bypass of system_entry.

    Per PHASE 1 REMEDIATION:
    - NO placeholder workflow IDs
    - NO placeholder stream registry entries
    - Stream registry entry created ONLY AFTER persistence exists
    - bg_id registration ONLY AFTER workflow_id is known and persistence exists
    """
    if not req.input or not req.input.strip():
        raise HTTPException(status_code=400, detail="input must not be empty")

    bg_id = str(_uuid_mod.uuid4())

    # Create a PENDING stream entry BEFORE thread spawn so the frontend poll never
    # gets a 404 during the LLM planning gap (which can be 2-10 seconds).
    # workflow_id is null here — that is the PENDING state. It is NOT a placeholder
    # workflow_id. The entry signals "session exists, workflow not yet created."
    # execute_from_input() will update this entry to ACTIVATING then ACTIVE.
    with _stream_registry_lock:
        _stream_registry[bg_id] = {
            "orchestrator_workflow_id": None,
            "workflow": None,
            "result": None,
            "status": "PENDING",
            "error": None,
        }

    t = threading.Thread(
        target=_run_workflow_wrapper,
        args=(bg_id, req.input),
        kwargs={"mode": "new"},
        daemon=True,
        name=f"stream-{bg_id[:8]}",
    )
    t.start()
    return {"bg_id": bg_id, "status": "PENDING"}


@app.get("/execute/stream/workflow_id/{bg_id}")
def stream_workflow_id(bg_id: str):
    """
    GET /execute/stream/workflow_id/{bg_id}
    Returns orchestrator workflow_id once planning completes (written by thread).

    Per PHASE 1 REMEDIATION:
    - Frontend may ONLY hydrate from persistence-backed workflows
    - Persistence validation required before returning to frontend
    """
    with _stream_registry_lock:
        entry = _stream_registry.get(bg_id)
    if entry is None:
        raise HTTPException(status_code=404, detail="bg_id not found")

    wf_id = entry.get("orchestrator_workflow_id")
    status = entry.get("status", "")

    # Internal bootstrap states (ACTIVATING, PERSISTED, PENDING_RECOVERY) must NOT
    # appear in stream schema. Return PENDING — frontend treats it as planning-in-progress.
    if status in ("ACTIVATING", "PERSISTED", "PENDING_RECOVERY"):
        return {
            "bg_id": bg_id,
            "workflow_id": None,
            "status": "PENDING",
            "result": None,
        }

    # === FRONTEND AUTHORITY ENFORCEMENT ===
    # Fast O(1) existence check — do NOT call validate_runtime_activation() here (full scan).
    if wf_id:
        if not _wf_persistence_exists(wf_id):
            _evict_workflow_state(wf_id, bg_id=bg_id, reason="stream_workflow_id_no_persistence")
            raise HTTPException(status_code=404, detail="workflow not found")

    # === RUNTIME OBSERVABILITY: runtime_activity ===
    # Per RUNTIME_REGISTRY_AND_EXECUTION_COORDINATION_CONTRACT_V1 §9:
    # Stream endpoint exposes runtime_activity for global frontend observability.
    # Stream registry cache preferred; falls back to authoritative runtime registry.
    _runtime_activity = entry.get("runtime_activity")
    if not _runtime_activity and wf_id and _get_workflow_state is not None:
        _runtime_state = _get_workflow_state(wf_id)
        if _runtime_state:
            _runtime_activity = _runtime_state.get("runtime_activity")

    response = {
        "bg_id": bg_id,
        "workflow_id": wf_id,
        "status": status,
        "runtime_activity": _runtime_activity,
    }

    workflow = entry.get("workflow")
    if workflow and isinstance(workflow, dict) and "steps" in workflow:
        projected = project_workflow_for_gui(workflow)
        projected["workflow_id"] = wf_id
        projected["status"] = entry["status"]
        response["result"] = projected
    elif entry.get("status") == "FAILED":
        stored_result = entry.get("result") or {}
        response["result"] = {
            "status": "FAILED",
            "reason": stored_result.get("reason") or entry.get("error") or "execution_failed",
            "workflow_id": wf_id,
            "steps": [],
            "outputs": [],
        }
    else:
        response["result"] = None

    return response



# =============================================================================
# PHASE 2.2 — WORKFLOW CONTROL (Per GUI_FUNCTIONALITY_CONTRACT_V1)
# =============================================================================

@app.post("/pause/{workflow_id}")
def pause_workflow_endpoint(workflow_id: str):
    """
    POST /pause/{workflow_id}
    Pause a specific workflow using state transition.
    Per STATE_TRANSITIONS_CONTRACT_V1: ACTIVE → PAUSED
    Per GUI_FUNCTIONALITY_CONTRACT_V1: ALL actions require workflow_id
    """
    result = pause_workflow(workflow_id)
    if result.get("status") == "failure":
        raise HTTPException(status_code=400, detail=result.get("reason"))
    
    # Per LIFECYCLE_AND_PROJECTION_AUTHORITY_CONTRACT_V1: Stream registry is projection-only
    # Update projection cache to mirror runtime registry (pause_workflow updates runtime registry)
    with _stream_registry_lock:
        for bg_id, entry in _stream_registry.items():
            if entry.get("orchestrator_workflow_id") == workflow_id:
                # Read authoritative lifecycle state from runtime registry and cache for projection
                runtime_state = _get_workflow_state(workflow_id)
                entry["status"] = runtime_state["status"] if runtime_state else "PAUSED"
                entry["runtime_activity"] = runtime_state.get("runtime_activity") if runtime_state else None
                # === LIFECYCLE SYNC BRIDGE (Phase 4G-A.9): sync into cached workflow dict ===
                _cached_wf = entry.get("workflow")
                if _cached_wf is not None and isinstance(_cached_wf, dict):
                    _cached_wf["status"] = runtime_state["status"] if runtime_state else "PAUSED"
                break

    # === CANONICAL PROJECTION EMISSION ON PAUSE ===
    # Per CANONICAL_PROJECTION_MODEL_V1 §5: projection MUST be emitted on lifecycle change.
    # pause_workflow() commits PAUSED to registry but does not emit canonical projection.
    # Emit now so /projection/{workflow_id} immediately reflects PAUSED lifecycle.
    # Failure-isolated: must not affect pause response.
    try:
        if _get_proj_mgr is not None:
            _wf_for_proj = None
            # Prefer in-memory workflow from stream registry (shallow copy to avoid race with execution thread)
            with _stream_registry_lock:
                for _p_bg_id, _p_entry in _stream_registry.items():
                    if _p_entry.get("orchestrator_workflow_id") == workflow_id:
                        _raw_wf = _p_entry.get("workflow")
                        _wf_for_proj = dict(_raw_wf) if isinstance(_raw_wf, dict) else None
                        break
            # Fallback to persistence if not in stream registry
            if _wf_for_proj is None:
                from system.orchestrator.persistence import load_active_workflows as _law_p
                for _wf_p in _law_p():
                    if _wf_p.get("id") == workflow_id:
                        _wf_for_proj = _wf_p
                        break
            if _wf_for_proj is not None and isinstance(_wf_for_proj, dict):
                _get_proj_mgr().emit_lifecycle_changed(_wf_for_proj, "PAUSED")
                print(f"[PROJECTION] Emitted PAUSED projection for {workflow_id}")
            else:
                print(f"[PROJECTION] Could not emit PAUSED projection for {workflow_id}: workflow not found")
    except Exception as _proj_e:
        print(f"[PROJECTION] PAUSED projection emission failed for {workflow_id}: {_proj_e}")

    return {"status": "ok", "paused": True, "workflow_id": workflow_id}


@app.post("/resume/{workflow_id}")
async def resume_workflow_endpoint(workflow_id: str):
    """
    POST /resume/{workflow_id}
    Resume a specific workflow using state transition.
    Per STATE_TRANSITIONS_CONTRACT_V1: PAUSED → ACTIVE
    Per GUI_FUNCTIONALITY_CONTRACT_V1: ALL actions require workflow_id
    """
    result = resume_workflow(workflow_id)
    if result.get("status") == "failure":
        raise HTTPException(status_code=400, detail=result.get("reason"))

    # Fast single-file load — do NOT call load_active_workflows() (full scan).
    from system.orchestrator.persistence import _active_workflow_path as _awp
    import json as _json
    workflow = None
    try:
        with open(_awp(workflow_id), "r", encoding="utf-8") as _f:
            workflow = _json.load(_f)
        if not isinstance(workflow, dict) or workflow.get("id") != workflow_id:
            workflow = None
    except Exception:
        workflow = None

    if workflow is None:
        raise HTTPException(status_code=404, detail="workflow_not_found")

    # Verify transition occurred — check authoritative runtime registry, NOT stale persisted dict.
    # Per LIFECYCLE_AND_PROJECTION_AUTHORITY_CONTRACT_V1: runtime registry is sole lifecycle authority.
    # Persisted dict may lag behind registry if save_workflow write was slightly delayed.
    _authoritative = _get_workflow_state(workflow_id)
    if not _authoritative or _authoritative.get("status") != "ACTIVE":
        raise HTTPException(status_code=400, detail="workflow_not_resumed")

    # Sync the loaded dict from authoritative registry ONLY.
    # Per PHASE VI: inject_authoritative_lifecycle_into_workflow replaces direct mirror mutation.
    from system.orchestrator.workflow_control import inject_authoritative_lifecycle_into_workflow
    inject_authoritative_lifecycle_into_workflow(workflow)

    # === PHASE-IVB: EXECUTION GENERATION COORDINATION ===
    # Increment generation to invalidate any stale execution threads from previous
    # pause/resume cycles or mutations. Per PHASE-IVA EXECUTION LEASE COORDINATION DESIGN AUDIT.
    try:
        from system.orchestrator.workflow_control import _workflow_state_registry, _workflow_state_lock
        with _workflow_state_lock:
            _current_gen = _workflow_state_registry.get(workflow_id, {}).get("execution_generation", 1)
            _workflow_state_registry[workflow_id]["execution_generation"] = _current_gen + 1
            print(f"[EXECUTION_GENERATION] Resume incremented workflow={workflow_id} generation={_current_gen + 1}")
    except Exception as e:
        print(f"[EXECUTION_GENERATION] Failed to increment generation for resume workflow={workflow_id}: {e}")

    # Find existing bg_id associated with this workflow_id
    # bg_id represents projection identity and stream session identity
    # Reuse same bg_id to maintain projection continuity
    bg_id = None
    with _stream_registry_lock:
        for existing_bg_id, entry in _stream_registry.items():
            if entry.get("orchestrator_workflow_id") == workflow_id:
                bg_id = existing_bg_id
                # Per LIFECYCLE_AND_PROJECTION_AUTHORITY_CONTRACT_V1: Stream registry is projection-only
                # Update projection cache to mirror runtime registry (resume_workflow updates runtime registry)
                # Read authoritative lifecycle state from runtime registry and cache for projection
                runtime_state = _get_workflow_state(workflow_id)
                entry["status"] = runtime_state["status"] if runtime_state else "ACTIVE"
                entry["runtime_activity"] = runtime_state.get("runtime_activity") if runtime_state else None
                # === LIFECYCLE SYNC BRIDGE (Phase 4G-A.9): sync into cached workflow dict before clearing ===
                _cached_wf = entry.get("workflow")
                if _cached_wf is not None and isinstance(_cached_wf, dict):
                    _cached_wf["status"] = runtime_state["status"] if runtime_state else "ACTIVE"
                entry["workflow"] = None  # Will be set by run_workflow
                entry["result"] = None  # Will be set by run_workflow
                entry["error"] = None
                break

    # If no existing bg_id found (edge case), create new one
    if bg_id is None:
        bg_id = str(_uuid_mod.uuid4())
        with _stream_registry_lock:
            # Per LIFECYCLE_AND_PROJECTION_AUTHORITY_CONTRACT_V1: Stream registry is projection-only
            # Initialize with ACTIVE as default projection (will be updated from runtime registry)
            _res_auth_new2 = _get_workflow_state(workflow_id)
            _stream_registry[bg_id] = {
                "orchestrator_workflow_id": workflow_id,
                "workflow": None,
                "result": None,
                "status": _res_auth_new2["status"] if _res_auth_new2 else "ACTIVE",
                "runtime_activity": _res_auth_new2.get("runtime_activity") if _res_auth_new2 else None,
                "error": None,
            }

    # Resume is async: start execution thread and return bg_id immediately.
    t = threading.Thread(
        target=_run_workflow_wrapper,
        args=(bg_id, workflow),
        kwargs={"mode": "resume"},
        daemon=True,
        name=f"resume-{bg_id[:8]}",
    )
    t.start()

    # Return bg_id immediately so frontend can attach stream poll.
    # Per LIFECYCLE_AND_PROJECTION_AUTHORITY_CONTRACT_V1 §RESUME RULES:
    # Resume MUST reuse same projection identity (bg_id) to maintain continuity.
    return {"status": "ok", "resumed": True, "workflow_id": workflow_id, "bg_id": bg_id}


@app.get("/status")
def get_status():
    """GET /status → user_control.get_control_state()"""
    return get_control_state()


# =============================================================================
# PHASE 2.3 — BACKGROUND WORKFLOWS
# =============================================================================

@app.post("/background/start")
def background_start(req: BackgroundStartRequest):
    """POST /background/start → background_manager.start_workflow()"""
    if not req.input or not req.input.strip():
        raise HTTPException(status_code=400, detail="input must not be empty")
    workflow_id = _bg_manager.start_workflow(execute_from_input, req.input)
    return {"status": "ok", "workflow_id": workflow_id}


@app.get("/background/list")
def background_list():
    """GET /background/list → background_manager.list_workflows()"""
    return {"workflows": _bg_manager.list_workflows()}


@app.get("/execute/stream/active")
def stream_active():
    """
    GET /execute/stream/active
    Returns all bg_id entries from _stream_registry that have a known workflow_id.

    Per PHASE 1 REMEDIATION:
    - Frontend may ONLY hydrate from persistence-backed workflows
    - NO placeholder workflow IDs (removed)
    - Persistence validation required before returning to frontend
    """
    # Snapshot candidates without holding the lock during I/O
    _snapshot = []
    with _stream_registry_lock:
        _snapshot = list(_stream_registry.items())

    # === PHASE XV-B TRACE LOGGING ===
    print("[STREAM_ACTIVE_SNAPSHOT]")
    print(f"  count={len(_snapshot)}")
    for _s_bgid, _s_entry in _snapshot:
        print(f"  bg_id={_s_bgid} workflow_id={_s_entry.get('orchestrator_workflow_id')} status={_s_entry.get('status')}")

    active = []
    _to_evict = []  # (wf_id, bg_id, reason) — evicted after iteration

    for bg_id, entry in _snapshot:
        wf_id = entry.get("orchestrator_workflow_id")
        # Per PHASE 1: NO placeholder entries
        if not wf_id:
            continue

        status = entry.get("status", "")

        # Frontend may ONLY see ACTIVE workflows.
        # ACTIVATING and PENDING_RECOVERY are pre-bootstrap states — exclude from frontend.
        if status in ("QUARANTINED", "ACTIVATING", "PENDING_RECOVERY"):
            if status == "QUARANTINED":
                _to_evict.append((wf_id, bg_id, "stream_active_quarantined_status"))
            continue

        # === FRONTEND AUTHORITY ENFORCEMENT ===
        # Fast O(1) existence check — do NOT call validate_runtime_activation() here (full scan).
        if not _wf_persistence_exists(wf_id):
            _to_evict.append((wf_id, bg_id, "stream_active_no_persistence"))
            continue

        active.append({
            "bg_id": bg_id,
            "workflow_id": wf_id,
            "status": status,
        })

    # Execute evictions outside the snapshot loop
    for _ev_wfid, _ev_bgid, _ev_reason in _to_evict:
        _evict_workflow_state(_ev_wfid, bg_id=_ev_bgid, reason=_ev_reason)

    # === PHASE XV-B TRACE LOGGING ===
    print("[STREAM_ACTIVE_RETURN]")
    print(f"  count={len(active)}")
    for _a_entry in active:
        print(f"  bg_id={_a_entry['bg_id']} workflow_id={_a_entry['workflow_id']} status={_a_entry['status']}")

    return {"active": active}


@app.get("/workflows/authoritative")
def get_authoritative_workflows():
    """
    GET /workflows/authoritative
    Returns authoritative workflow enumeration from Lifecycle Registry.

    Per LIFECYCLE_AUTHORITY_CONTRACT_V1 §WORKFLOW ENUMERATION RULES:
    - Workflow enumeration MUST originate from authoritative workflow identity state.
    - Stream registry MUST NOT act as recovery authority.

    Per SYSTEM_CONVERGENCE_AND_RECOVERY_CONTRACT_V1 §14:
    - Frontend heuristic workflow restoration is PROHIBITED.
    - Stream-derived workflow identity is PROHIBITED.

    SOURCE OF TRUTH:
    - _workflow_state_registry (Lifecycle Authority)
    - persistence-backed workflow identity

    DO NOT:
    - source from stream registry
    - source from projections
    - source from frontend state
    """
    from system.orchestrator.workflow_control import _workflow_state_registry, _workflow_state_lock

    # Build reverse bg_id lookup for transport convenience
    wf_to_bg = {}
    try:
        if _load_bg_id_map:
            _bg_map = _load_bg_id_map()
            for bg_id, wf_id in _bg_map.items():
                wf_to_bg.setdefault(wf_id, []).append(bg_id)
    except Exception:
        pass

    workflows = []
    with _workflow_state_lock:
        for wf_id, state in _workflow_state_registry.items():
            # Hard guard: persistence must exist for any returned workflow
            if not _wf_persistence_exists(wf_id):
                continue
            # Phase 4G-A.9: UNKNOWN MUST NOT leak into operator UI.
            # Use None so frontend renders Pending / no label.
            status = state.get("status")
            # Recoverable = non-terminal, non-quarantined
            # CANCELLED is immutable terminal — must NOT be recoverable
            recoverable = status not in ("COMPLETED", "FAILED", "CANCELLED", "QUARANTINED")
            workflows.append({
                "workflow_id": wf_id,
                "status": status,
                "recoverable": recoverable,
                "execution_generation": state.get("execution_generation", 1),
                "bg_ids": wf_to_bg.get(wf_id, []),
            })

    # === PHASE XV-B TRACE LOGGING ===
    print("[AUTHORITATIVE_WORKFLOWS]")
    print(f"  count={len(workflows)}")
    for w in workflows:
        print(f"  workflow_id={w['workflow_id']} status={w['status']} recoverable={w['recoverable']} bg_ids={w['bg_ids']}")

    return {"workflows": workflows}


@app.get("/background/status/{workflow_id}")
def background_status(workflow_id: str):
    """GET /background/status/{id} → background_manager.get_status(id)"""
    status = _bg_manager.get_status(workflow_id)
    if status is None:
        raise HTTPException(status_code=404, detail="workflow not found")
    return status


# =============================================================================
# PHASE 2.5 — TRACE RETRIEVAL
# =============================================================================

@app.get("/trace/{workflow_id}")
def get_trace(workflow_id: str):
    """
    GET /trace/{workflow_id}
    Returns trace data for specific workflow.
    Tries memory first, then file fallback.
    Returns 404 if not found.
    Trace data is projected to remove execution fields from steps.
    """
    # Try memory first (current collectors)
    from system.orchestrator import trace_collector
    trace = trace_collector.get_trace(workflow_id)
    
    if trace is None:
        # Fallback to file storage
        try:
            import os
            import json
            trace_file = os.path.join("traces", f"{workflow_id}.json")
            if os.path.exists(trace_file):
                with open(trace_file, "r") as f:
                    trace = json.load(f)
        except Exception:
            # File read error - treat as not found
            pass
    
    if trace is None:
        raise HTTPException(status_code=404, detail="trace not found")
    
    # Apply projection to trace steps if present
    if trace and isinstance(trace, dict) and "steps" in trace:
        # Clean trace steps - remove execution_result and tool_call
        cleaned_steps = []
        for step in trace.get("steps", []):
            if not isinstance(step, dict):
                cleaned_steps.append(step)
                continue
            
            cleaned_step = {
                "step_id": step.get("step_id"),
                "status": step.get("status"),
                "purpose": step.get("purpose"),
                "retries": step.get("retries", 0)
            }
            
            # Keep governance_decision if present
            if step.get("governance_decision"):
                cleaned_step["governance_decision"] = step["governance_decision"]
            
            cleaned_steps.append(cleaned_step)
        
        trace["steps"] = cleaned_steps
    
    return trace


# =============================================================================
# PHASE 2.6 — LIVE EVENT STREAMING (STATE-DRIVEN)
# =============================================================================

@app.get("/events/{workflow_id}")
def get_events(
    workflow_id: str,
    since: int = -1,
    since_sequence: int = -1,
    limit: int = 100,
):
    """
    GET /events/{workflow_id}?since={event_id}&since_sequence={seq}&limit={count}
    Returns live events for workflow state streaming.

    Per HAND_ARCHITECTURE_V2 Section 15: LIVE mode provides step-by-step visibility
    Per CONTROL_MODEL: Events are advisory, non-authoritative
    Per TRACE_LOGGING_CONTRACT_V1: UI uses STATE (events), not trace, for live updates

    Per REPLAY_QUERY_PAGINATION:
    - since_sequence (bus_sequence_id) is the authoritative monotonic cursor.
    - since (event_id index) is legacy; preserved for backward compatibility.

    Args:
        since: Return only events after this event index (legacy, optional)
        since_sequence: Return only events with bus_sequence_id > since_sequence (authoritative)
        limit: Maximum events to return (default 100)

    Returns:
        List of events with:
        - event_type: step_started, step_completed, governance_decision, etc.
        - timestamp: ISO8601 timestamp
        - data: Event payload (step_id, status, result, etc.)
    """
    from system.interface.event_bus import get_events as _get_events

    # Prefer authoritative since_sequence cursor; fall back to legacy since_event_id
    since_seq = since_sequence if since_sequence >= 0 else None
    since_event_id = since if since >= 0 and since_seq is None else None
    events = _get_events(
        workflow_id,
        since_event_id=since_event_id,
        since_sequence=since_seq,
        limit=limit,
    )

    # Per PROJECTION_CONTINUITY_CONTRACT_V1 §6 (SUB-PHASE 3D):
    # Sort by bus_sequence_id (monotonic per-workflow counter) when available;
    # fall back to timestamp for backward compatibility.
    # bus_sequence_id is deterministic; timestamp sort can have same-ms ties.
    # Per PROJECTION_CONTINUITY_CONTRACT_V1 §11: detect invalid stream ordering.
    has_seq = any("bus_sequence_id" in e for e in events)
    if has_seq:
        events.sort(key=lambda e: e.get("bus_sequence_id", 0))
    else:
        events.sort(key=lambda e: e.get("timestamp", ""))

    # Add sequential IDs for since-based polling (backward compatibility)
    base = since + 1 if since >= 0 else 0
    for i, event in enumerate(events):
        event["event_id"] = base + i

    # Per PROJECTION_CONTINUITY_CONTRACT_V1 §11 (SUB-PHASE 3D):
    # Expose latest_bus_sequence_id for reconnect continuity gap detection.
    from system.interface.event_bus import get_latest_sequence as _get_latest_seq
    latest_bus_seq = _get_latest_seq(workflow_id)

    return {
        "workflow_id": workflow_id,
        "events": events,
        "count": len(events),
        "latest_event_id": base + len(events) - 1 if events else since,
        "latest_bus_sequence_id": latest_bus_seq,  # authoritative reconnect cursor
    }


# =============================================================================
# PHASE 2.4 — APPROVAL
# =============================================================================

@app.get("/approval/pending")
def approval_pending():
    """
    GET /approval/pending
    Returns list of steps currently awaiting GUI approval.
    Steps are projected to remove execution-only fields (tool_call, execution_result).
    """
    pending = [
        {
            "step_id": sid,
            "step": project_step_for_approval(entry["step"]),
        }
        for sid, entry in _pending_approvals.items()
        if not entry.get("resolved", False)
    ]
    return {"pending": pending}


@app.post("/approve")
def approve_step(req: ApprovalRequest):
    """
    POST /approve  { workflow_id, step_id, approved: true }
    Resolves the pending approval — MUST NOT bypass governance.
    Governance already decided BLOCK; this only records user choice.
    Per GUI_FUNCTIONALITY_CONTRACT_V1: ALL actions require workflow_id
    """
    entry = _pending_approvals.get(req.step_id)
    if entry is None:
        raise HTTPException(status_code=404, detail="no pending approval for that step_id")
    if entry.get("resolved"):
        raise HTTPException(status_code=409, detail="already resolved")
    entry["approved"] = req.approved
    entry["resolved"] = True
    future: asyncio.Future = entry.get("future")
    if future and not future.done():
        future.get_loop().call_soon_threadsafe(future.set_result, req.approved)
    return {"status": "ok", "workflow_id": req.workflow_id, "step_id": req.step_id, "approved": req.approved}


@app.post("/deny")
def deny_step(req: ApprovalRequest):
    """
    POST /deny  { workflow_id, step_id, approved: false }
    Convenience alias — delegates to /approve with approved=False.
    Per GUI_FUNCTIONALITY_CONTRACT_V1: ALL actions require workflow_id
    """
    req.approved = False
    return approve_step(req)


# =============================================================================
# PHASE 5 — DEBUG
# =============================================================================

@app.get("/debug/events")
def debug_events():
    """GET /debug/events — dump all active workflow IDs and event counts in the bus."""
    from system.interface.event_bus import get_event_bus
    bus = get_event_bus()
    workflow_ids = bus.get_workflow_ids()
    summary = {}
    for wid in workflow_ids:
        events = bus.get_events(wid)
        summary[wid] = {
            "count": len(events),
            "types": [e.get("event_type") for e in events],
        }
    return {"active_workflows": workflow_ids, "summary": summary, "failure_count": bus.get_failure_count()}


@app.get("/debug/control_state")
def debug_control_state():
    """GET /debug/control_state — raw control state dump"""
    return {
        "control_state": get_control_state(),
        "pending_approvals": list(_pending_approvals.keys()),
        "background_count": _bg_manager.active_count(),
    }


# =============================================================================
# PHASE 2.7 — PLAN CONTROL (Per PLAN_CONTROL_CONTRACT_V1)
# =============================================================================

@app.get("/plan/{workflow_id}")
def get_plan_endpoint(workflow_id: str):
    """
    GET /plan/{workflow_id}
    Retrieve the current execution plan for a workflow.
    """
    result = get_plan(workflow_id)
    if result.get("status") == "failure":
        raise HTTPException(status_code=404, detail=result.get("reason"))
    return result


@app.post("/plan/edit")
def edit_step_endpoint(req: PlanEditRequest):
    """
    POST /plan/edit
    Edit a step in the workflow plan.

    Per MUTATION_AUTHORITY_CONSOLIDATION:
    - Legacy endpoint now routes through canonical mutation authority
    - Thin adapter only — delegates to request_plan_mutation()
    - Preserves backward compatibility while ensuring contract compliance

    Per PLAN_CONTROL_CONTRACT_V1: validates edit and dependency graph.
    Per CANONICAL_PROJECTION_MODEL_V1 §7: uses canonical mutation flow.
    """
    if _request_plan_mutation is None:
        raise HTTPException(status_code=503, detail="mutation_manager_unavailable")

    # === MUTATION AUTHORITY CONSOLIDATION ===
    # Route through canonical mutation authority instead of direct workflow_control call
    # This ensures: validation, trace logging, projection invalidation, resurrection bridge
    result = _request_plan_mutation(
        workflow_id=req.workflow_id,
        mutation_type="edit_step",
        payload={"step_id": req.step_id, "updates": req.updates},
        actor="user",
    )

    if result.get("status") == "failure":
        raise HTTPException(status_code=400, detail=result.get("reason"))

    # === EXECUTION RESURRECTION BRIDGE ===
    # Per ORCHESTRATOR_EXECUTION_CONTRACT: edit mutations that revive terminal workflows
    # MUST trigger execution re-entry. Already handled by mutation manager for edit_step.
    if result.get("status") == "success":
        _bg_id = _maybe_resurrect_execution(req.workflow_id)
        if _bg_id is not None:
            result["bg_id"] = _bg_id
            result["execution_resumed"] = True

    return result


@app.post("/plan/add")
def add_step_endpoint(req: PlanAddRequest):
    """
    POST /plan/add
    Add a new step to the workflow plan.

    Per MUTATION_AUTHORITY_CONSOLIDATION:
    - Legacy endpoint now routes through canonical mutation authority
    - Thin adapter only — delegates to request_plan_mutation()
    - Preserves backward compatibility while ensuring contract compliance

    Per PLAN_CONTROL_CONTRACT_V1: validates and appends step.
    Per CANONICAL_PROJECTION_MODEL_V1 §7: uses canonical mutation flow.
    """
    if _request_plan_mutation is None:
        raise HTTPException(status_code=503, detail="mutation_manager_unavailable")

    # === MUTATION AUTHORITY CONSOLIDATION ===
    # Route through canonical mutation authority instead of direct workflow_control call
    # This ensures: validation, trace logging, projection invalidation
    result = _request_plan_mutation(
        workflow_id=req.workflow_id,
        mutation_type="add_step",
        payload={"step_data": req.step_data},
        actor="user",
    )

    if result.get("status") == "failure":
        raise HTTPException(status_code=400, detail=result.get("reason"))

    return result


@app.post("/plan/remove")
def remove_step_endpoint(req: PlanRemoveRequest):
    """
    POST /plan/remove
    Remove a step from the workflow plan.

    Per MUTATION_AUTHORITY_CONSOLIDATION:
    - Legacy endpoint now routes through canonical mutation authority
    - Thin adapter only — delegates to request_plan_mutation()
    - Preserves backward compatibility while ensuring contract compliance

    Per PLAN_CONTROL_CONTRACT_V1: rejects if step is COMPLETED or has dependents.
    Per CANONICAL_PROJECTION_MODEL_V1 §7: uses canonical mutation flow.
    """
    if _request_plan_mutation is None:
        raise HTTPException(status_code=503, detail="mutation_manager_unavailable")

    # === MUTATION AUTHORITY CONSOLIDATION ===
    # Route through canonical mutation authority instead of direct workflow_control call
    # This ensures: validation, trace logging, projection invalidation
    result = _request_plan_mutation(
        workflow_id=req.workflow_id,
        mutation_type="remove_step",
        payload={"step_id": req.step_id},
        actor="user",
    )

    if result.get("status") == "failure":
        raise HTTPException(status_code=400, detail=result.get("reason"))

    return result


@app.post("/plan/reorder")
def reorder_steps_endpoint(req: PlanReorderRequest):
    """
    POST /plan/reorder
    Reorder steps in the workflow plan.

    Per MUTATION_AUTHORITY_CONSOLIDATION:
    - TODO: Reorder requires MUTATION_TYPE_REORDER_STEP addition to mutation manager
    - Currently uses direct workflow_control path (validated but no invalidation/tracing)
    - Future: route through request_plan_mutation() when reorder type added

    Per PLAN_CONTROL_CONTRACT_V1: validates dependency constraints.
    """
    # === MUTATION AUTHORITY GAP ===
    # reorder_steps is NOT in ALLOWED_MUTATION_TYPES — cannot route through mutation manager yet
    # The validate_reorder function exists in mutation_validation.py but is not wired to manager
    # This is a KNOWN GAP requiring: add MUTATION_TYPE_REORDER_STEP + _handle_reorder_step()
    # For now: direct call with validation but NO projection invalidation, NO trace logging
    # Workaround: mutation manager handles add/remove/edit; reorder deferred
    result = reorder_steps(req.workflow_id, req.new_order)
    if result.get("status") == "failure":
        raise HTTPException(status_code=400, detail=result.get("reason"))
    return result


# =============================================================================
# PHASE 2.8 — CONTROL ACTIONS (Per ORCHESTRATOR_CONTRACT_V2)
# =============================================================================

@app.post("/step/retry")
def retry_step_endpoint(req: RetryStepRequest):
    """
    POST /step/retry
    Retry a failed or blocked step.

    Per MUTATION_AUTHORITY_CONSOLIDATION:
    - Legacy endpoint now routes through canonical mutation authority
    - Thin adapter only — delegates to request_plan_mutation()
    - Preserves backward compatibility while ensuring contract compliance

    Requires workflow_id and step_id.
    """
    if _request_plan_mutation is None:
        raise HTTPException(status_code=503, detail="mutation_manager_unavailable")

    # === MUTATION AUTHORITY CONSOLIDATION ===
    # Route through canonical mutation authority instead of direct workflow_control call
    # This ensures: validation, trace logging, projection invalidation, resurrection bridge
    result = _request_plan_mutation(
        workflow_id=req.workflow_id,
        mutation_type="retry_step",
        payload={"step_id": req.step_id},
        actor="user",
    )

    if result.get("status") == "failure":
        raise HTTPException(status_code=400, detail=result.get("reason"))

    # === EXECUTION RESURRECTION BRIDGE ===
    # Per ORCHESTRATOR_EXECUTION_CONTRACT: retry mutations that revive terminal workflows
    # MUST trigger execution re-entry. Mutation manager handles ACTIVE transition;
    # this bridge spawns the execution thread.
    # Note: _maybe_resurrect_execution is also called internally by mutation manager;
    # this is a safety net for the legacy endpoint path.
    if result.get("status") == "success":
        _bg_id = _maybe_resurrect_execution(req.workflow_id)
        if _bg_id is not None:
            result["bg_id"] = _bg_id
            result["execution_resumed"] = True

    return result


@app.post("/workflow/stop")
def stop_workflow_endpoint(req: StopWorkflowRequest):
    """
    POST /workflow/stop
    Stop a running workflow via intentional operator cancellation.
    Per WORKFLOW_CANCELLATION_AND_TERMINALIZATION_CONTRACT_V1:
      ACTIVE|PAUSED|BLOCKED → CANCELLED (immutable terminal)
    """
    result = cancel_workflow(req.workflow_id, reason="user_stop")
    if result.get("status") == "failure":
        raise HTTPException(status_code=400, detail=result.get("reason"))
    return result


@app.post("/workflow/cancel")
def cancel_workflow_endpoint(req: StopWorkflowRequest):
    """
    POST /workflow/cancel
    Cancel a running workflow — authoritative immutable terminal convergence.
    Per WORKFLOW_CANCELLATION_AND_TERMINALIZATION_CONTRACT_V1:
      ACTIVE|PAUSED|BLOCKED → CANCELLED
    """
    result = cancel_workflow(req.workflow_id, reason="user_cancel")
    if result.get("status") == "failure":
        raise HTTPException(status_code=400, detail=result.get("reason"))
    return result


# =============================================================================
# PHASE 4B.1 — PLAN MUTATION INTENT ENDPOINT
# =============================================================================

@app.post("/workflow/{workflow_id}/mutation")
def plan_mutation_endpoint(workflow_id: str, req: MutationRequest):
    """
    POST /workflow/{workflow_id}/mutation

    Mutation intent endpoint — transport-only.

    Per CANONICAL_PROJECTION_MODEL_V1 §7 (Projection Mutation Flow):
    - API layer acts as schema validation boundary and intent routing layer only
    - API MUST NOT own mutation authority
    - API MUST NOT synthesize workflow state
    - API forwards mutation intent to orchestrator-owned PlanMutationManager

    Per GUI_FUNCTIONALITY_CONTRACT_V1 §LIFECYCLE ACTION MODEL:
    - GUI actions REQUEST mutations — they do NOT define them

    Allowed mutation_type values (this phase):
      edit_step, add_step, remove_step, retry_step

    Payload per mutation_type:
      edit_step:    {step_id, updates: {field: value, ...}}
      add_step:     {step_data: {...}}
      remove_step:  {step_id}
      retry_step:   {step_id}
    """
    if _request_plan_mutation is None:
        raise HTTPException(status_code=503, detail="mutation_manager_unavailable")

    # Schema validation boundary: reject unknown mutation types before dispatch
    if req.mutation_type not in _ALLOWED_MUTATION_TYPES:
        raise HTTPException(
            status_code=400,
            detail=f"unknown_mutation_type:{req.mutation_type}"
        )

    # Forward intent to orchestrator-owned mutation authority
    result = _request_plan_mutation(
        workflow_id=workflow_id,
        mutation_type=req.mutation_type,
        payload=req.payload,
        actor=req.actor or "user",
    )

    if result.get("status") == "failure":
        raise HTTPException(status_code=400, detail=result.get("reason", "mutation_failed"))

    # === EXECUTION RESURRECTION BRIDGE (Phase 2 — Retry/Edit Runtime Re-entry) ===
    # Per ORCHESTRATOR_EXECUTION_CONTRACT: mutations that revive a terminal workflow MUST
    # trigger execution re-entry.  retry_step and edit_step write ACTIVE into the registry
    # via _update_workflow_state, but the original run_workflow thread has already exited.
    # _maybe_resurrect_execution detects registry ACTIVE and spawns a new run_workflow
    # thread, identical to the /resume/{workflow_id} re-entry path.
    # Only triggered for mutation types that can revive execution; harmless for others.
    if req.mutation_type in ("retry_step", "edit_step"):
        _bg_id = _maybe_resurrect_execution(workflow_id)
        if _bg_id is not None:
            result["bg_id"] = _bg_id
            result["execution_resumed"] = True

    return result


# =============================================================================
# PHASE 4A.0 — CANONICAL PROJECTION TRANSPORT
# =============================================================================

@app.get("/projection/{workflow_id}")
def get_canonical_projection(workflow_id: str):
    """
    GET /projection/{workflow_id}
    Returns the latest canonical WorkflowProjection for a workflow.

    Per PHASE 1 REMEDIATION:
    - Frontend may ONLY hydrate from persistence-backed workflows
    - Persistence validation required before returning to frontend

    Per CANONICAL_PROJECTION_MODEL_V1:
    - API is transport layer ONLY
    - API does NOT own projection truth
    - API does NOT mutate projection lifecycle
    - API does NOT synthesize workflow state

    Per CANONICAL_PROJECTION_MODEL_V1 §3 (Projection Identity):
    Response MUST include: workflow_id, projection_type, projection_version,
    projection_timestamp

    Returns 404 if no projection has been emitted for workflow_id.
    Returns 503 if projection manager is unavailable.
    """
    # === FRONTEND AUTHORITY ENFORCEMENT ===
    # Fast O(1) existence check — do NOT call validate_runtime_activation() here (full scan).
    if not _wf_persistence_exists(workflow_id):
        raise HTTPException(status_code=404, detail="workflow_not_found")

    if _get_proj_mgr is None:
        raise HTTPException(status_code=503, detail="projection_manager_unavailable")

    try:
        proj_mgr = _get_proj_mgr()
        projection = proj_mgr.get_latest_projection(workflow_id)
    except Exception:
        raise HTTPException(status_code=503, detail="projection_read_error")

    if projection is None:
        raise HTTPException(status_code=404, detail="projection_not_found")

    # Schema validation boundary: ensure projection identity is complete
    # Per CANONICAL_PROJECTION_MODEL_V1 §9 (API Boundary Rules)
    if validate_projection_identity is not None:
        if not validate_projection_identity(projection):
            raise HTTPException(status_code=500, detail="projection_identity_invalid")

    return projection


@app.get("/projection/{workflow_id}/version")
def get_projection_version(workflow_id: str):
    """
    GET /projection/{workflow_id}/version
    Returns the current projection version and state for a workflow.

    Per CANONICAL_PROJECTION_MODEL_V1 §4 (Projection Versioning):
    Enables frontend to detect when projection has been updated
    without fetching the full projection payload.

    API is transport-only: reads from ProjectionManager, does not mutate.
    """
    if _get_proj_mgr is None:
        raise HTTPException(status_code=503, detail="projection_manager_unavailable")

    try:
        proj_mgr = _get_proj_mgr()
        version = proj_mgr.get_projection_version(workflow_id)
        state = proj_mgr.get_projection_state(workflow_id)
    except Exception:
        raise HTTPException(status_code=503, detail="projection_read_error")

    if state is None:
        raise HTTPException(status_code=404, detail="projection_not_found")

    return {
        "workflow_id": workflow_id,
        "projection_version": version,
        "projection_state": state,
    }


@app.get("/projection/{workflow_id}/continuity")
def get_projection_continuity(workflow_id: str):
    """
    GET /projection/{workflow_id}/continuity
    Returns projection continuity diagnostics for a workflow.

    Per PROJECTION_CONTINUITY_CONTRACT_V1 §11 (SUB-PHASE 3E):
    Exposes continuity context for reconnect gap detection and stale repair.

    Returns:
    - projection_version: current version
    - projection_state: ACTIVE / STALE / INVALIDATED / TERMINAL
    - continuity_anchor: last confirmed synchronized version
    - stale_rejections: count of rejected stale projections
    - is_terminal: whether projection is in terminal state
    - has_projection: whether any projection has been emitted
    - latest_bus_sequence_id: current bus sequence for gap detection

    API is transport-only — does NOT mutate projection state.
    """
    if _get_proj_mgr is None:
        raise HTTPException(status_code=503, detail="projection_manager_unavailable")

    try:
        proj_mgr = _get_proj_mgr()
        summary = proj_mgr.get_continuity_summary(workflow_id)
    except Exception:
        raise HTTPException(status_code=503, detail="projection_read_error")

    # Enrich with bus sequence for reconnect gap detection
    from system.interface.event_bus import get_latest_sequence as _get_latest_seq
    summary["latest_bus_sequence_id"] = _get_latest_seq(workflow_id)

    return summary


# =============================================================================
# PHASE 4A.1 — RUNTIME OBSERVABILITY + DETERMINISTIC VALIDATION SUPPORT
# =============================================================================
# Per VALIDATION_ARCHITECTURE.txt §9 + WINDSURF_EXECUTION_TASK:
# Minimal read-only runtime inspection surfaces for debugging and
# deterministic survivability validation. NO authority inversion.
# =============================================================================

@app.get("/runtime/inspect/{workflow_id}")
def runtime_inspect(workflow_id: str):
    """
    GET /runtime/inspect/{workflow_id}
    Returns comprehensive runtime inspection metadata for debugging and validation.

    Per VALIDATION_ARCHITECTURE.txt §9.4: Runtime Survivability Validation
    Per EXECUTION_IDENTITY_AND_REPLAY_CONTRACT_V1: execution_generation visibility
    Per SYSTEM_CONVERGENCE_AND_RECOVERY_CONTRACT_V1: registry state visibility

    READ-ONLY: Does NOT mutate runtime state, define authority, or synthesize truth.
    Data sources: runtime registry (lifecycle authority), projection layer (read-model).

    Returns:
    - workflow_id: target workflow
    - lifecycle_status: authoritative status from runtime registry
    - execution_generation: current generation counter (mutation/retry invalidation)
    - persistence_exists: whether workflow has persisted state
    - active_execution: metadata about active execution context (if any)
    - projection_metadata: version/timestamp from projection layer
    - retry_lineage: retry count and history (if available)
    - timing_metadata: last lifecycle commit, projection refresh (if available)
    """
    from system.orchestrator.workflow_control import _workflow_state_registry, _workflow_state_lock

    result = {
        "workflow_id": workflow_id,
        "lifecycle_status": None,
        "execution_generation": None,
        "persistence_exists": False,
        "active_execution": None,
        "projection_metadata": None,
        "retry_lineage": None,
        "timing_metadata": None,
        "observability_timestamp": datetime.now(timezone.utc).isoformat(),
    }

    # 1. Authoritative runtime registry state (lifecycle authority)
    with _workflow_state_lock:
        if workflow_id in _workflow_state_registry:
            state = _workflow_state_registry[workflow_id]
            result["lifecycle_status"] = state.get("status", "UNKNOWN")
            result["execution_generation"] = state.get("execution_generation", 1)
            result["retry_lineage"] = {
                "retry_count": state.get("retry_count", 0),
                "last_retry_at": state.get("last_retry_at"),
            }
            # Timing metadata if available
            if "last_status_change" in state:
                result["timing_metadata"] = {
                    "last_lifecycle_commit": state.get("last_status_change"),
                }

    # 2. Persistence existence check
    result["persistence_exists"] = _wf_persistence_exists(workflow_id)

    # 3. Active execution context from stream registry (projection-only cache)
    with _stream_registry_lock:
        for bg_id, entry in _stream_registry.items():
            if entry.get("orchestrator_workflow_id") == workflow_id:
                result["active_execution"] = {
                    "bg_id": bg_id,
                    "stream_status": entry.get("status"),  # projection cache only
                    "has_result": entry.get("result") is not None,
                    "has_error": entry.get("error") is not None,
                }
                break

    # 4. Projection metadata (read-model)
    if _get_proj_mgr:
        try:
            proj_mgr = _get_proj_mgr()
            proj_version = proj_mgr.get_projection_version(workflow_id)
            proj_state = proj_mgr.get_projection_state(workflow_id)
            if proj_state:
                result["projection_metadata"] = {
                    "version": proj_version,
                    "state": proj_state,
                    "timestamp": proj_state.get("projection_timestamp"),
                }
                # Enrich timing metadata
                if result["timing_metadata"] is None:
                    result["timing_metadata"] = {}
                result["timing_metadata"]["last_projection_refresh"] = proj_state.get("projection_timestamp")
        except Exception:
            pass  # Projection unavailable is non-fatal for observability

    # === PHASE XV-B TRACE LOGGING ===
    print("[RUNTIME_INSPECT]")
    print(f"  workflow_id={workflow_id}")
    print(f"  lifecycle_status={result['lifecycle_status']}")
    print(f"  execution_generation={result['execution_generation']}")
    print(f"  persistence_exists={result['persistence_exists']}")
    print(f"  active_execution={result['active_execution'] is not None}")

    return result


@app.get("/runtime/registry/summary")
def runtime_registry_summary():
    """
    GET /runtime/registry/summary
    Returns summary of runtime registry state for debugging and validation.

    Per VALIDATION_ARCHITECTURE.txt §9: Runtime observability for survivability debugging.
    Per LIFECYCLE_AUTHORITY_CONTRACT_V1: Runtime registry is sole lifecycle authority.

    READ-ONLY: Does NOT expose internal registry references or enable mutation.
    Returns aggregated counts and workflow state distribution.

    Returns:
    - total_workflows: count in runtime registry
    - status_distribution: count by lifecycle status
    - execution_generations: list of (workflow_id, generation) for validation
    - stream_registry_count: active stream entries
    - observability_timestamp: inspection time
    """
    try:
        from system.orchestrator.workflow_control import _workflow_state_registry, _workflow_state_lock

        result = {
            "total_workflows": 0,
            "status_distribution": {},
            "execution_generations": [],
            "stream_registry_count": 0,
            "observability_timestamp": datetime.now(timezone.utc).isoformat(),
        }

        # 1. Runtime registry summary (lifecycle authority)
        with _workflow_state_lock:
            result["total_workflows"] = len(_workflow_state_registry)
            for wf_id, state in _workflow_state_registry.items():
                status = state.get("status", "UNKNOWN")
                result["status_distribution"][status] = result["status_distribution"].get(status, 0) + 1
                # Include execution_generation for stale-owner validation
                result["execution_generations"].append({
                    "workflow_id": wf_id,
                    "execution_generation": state.get("execution_generation", 1),
                    "status": status,
                })

        # 2. Stream registry count (projection cache)
        with _stream_registry_lock:
            result["stream_registry_count"] = len(_stream_registry)

        # === PHASE XV-B TRACE LOGGING ===
        print("[RUNTIME_REGISTRY_SUMMARY]")
        print(f"  total_workflows={result['total_workflows']}")
        print(f"  status_distribution={result['status_distribution']}")
        print(f"  stream_registry_count={result['stream_registry_count']}")

        return result
    except Exception as e:
        import traceback
        print(f"[RUNTIME_REGISTRY_SUMMARY_ERROR] {e}")
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Runtime registry summary error: {type(e).__name__}: {e}")


# =============================================================================
# TEST/ADMIN ONLY — AUTHORITATIVE RUNTIME RESET
# =============================================================================
# Per RUNTIME_REGISTRY_AND_EXECUTION_COORDINATION_CONTRACT_V1 §7:
#   Orphan runtime artifacts may be invalidated or rebuilt without affecting
#   lifecycle authority.
# Per LIFECYCLE_AND_PROJECTION_AUTHORITY_CONTRACT_V1:
#   Terminalization MUST terminate execution and retry workers.
# Per STATE_TRANSITIONS_CONTRACT_V1: ACTIVE|PAUSED|BLOCKED|ACTIVATING|PENDING_RECOVERY → FAILED
#
# WARNING: This endpoint is TEST/ADMIN SCOPED ONLY. It is NOT a GUI feature.
# It safely terminates active workflows and clears runtime coordination state
# to ensure test isolation. It does NOT redesign orchestration or weaken
# authority boundaries.
# =============================================================================

@app.post("/admin/test/reset_runtime")
def reset_runtime():
    """
    TEST/ADMIN ONLY: Authoritative runtime reset.

    Safely terminates all active workflows via lifecycle authority,
    clears runtime coordination state, and recreates the execution executor.

    Reset sequence (all steps failure-isolated):
      1. Stop all active workflows via stop_workflow() (authoritative terminal convergence)
      2. Cooperative exit window for execution loops
      3. Shutdown ThreadPoolExecutor and create fresh executor
      4. Clear _workflow_state_registry
      5. Clear _stream_registry
      6. Clear _bg_manager tracking
      7. Clear _pending_approvals
      8. Clear projection stores
      9. Clear bg_id_map persistence
      10. Delete disk artifacts (active workflows, checkpoints, bg_id_map)
    """
    from system.orchestrator.workflow_control import _workflow_state_registry, _workflow_state_lock

    stopped_count = 0
    evicted_count = 0

    # ── PHASE 1: Authoritative terminal convergence for active workflows ──
    with _workflow_state_lock:
        wf_ids = list(_workflow_state_registry.keys())

    for wf_id in wf_ids:
        try:
            state = _get_workflow_state(wf_id)
            if state and state.get("status") in ("ACTIVE", "PAUSED", "BLOCKED", "ACTIVATING", "PENDING_RECOVERY"):
                result = stop_workflow(wf_id)
                if result.get("status") == "success":
                    stopped_count += 1
                else:
                    # Fallback: mark registry FAILED directly if stop_workflow failed
                    _update_runtime_registry_only(wf_id, "FAILED", "reset_evict_fallback")
                    evicted_count += 1
            else:
                # Already terminal or missing — mark FAILED to ensure no stale active entry
                _update_runtime_registry_only(wf_id, "FAILED", "reset_cleanup")
                evicted_count += 1
        except Exception:
            pass

    print(f"[RESET] stopped={stopped_count} evicted={evicted_count}")

    # ── PHASE 2: Cooperative exit window ──
    # Execution loops check registry at step boundaries. Give them a brief
    # window to observe FAILED and exit cooperatively.
    import time
    time.sleep(2)

    # ── PHASE 2b: Wait for BackgroundManager threads ──
    # BackgroundManager threads are NOT part of ThreadPoolExecutor.
    # Old threads must exit before new tests start to avoid LLM API contention.
    try:
        with _bg_manager._lock:
            _bg_entries = list(_bg_manager._workflows.items())
        for _wid, _entry in _bg_entries:
            _thread = _entry.get("thread")
            if _thread is not None and _thread.is_alive():
                _thread.join(timeout=5)
    except Exception:
        pass

    # ── PHASE 3: Executor shutdown and recreation ──
    global _executor
    try:
        _executor.shutdown(wait=False, cancel_futures=True)
    except Exception:
        pass
    _executor = ThreadPoolExecutor(max_workers=4)

    # ── PHASE 4: Clear runtime registries ──
    with _workflow_state_lock:
        _workflow_state_registry.clear()

    with _stream_registry_lock:
        _stream_registry.clear()

    # ── PHASE 5: Clear background manager tracking ──
    with _bg_manager._lock:
        _bg_manager._workflows.clear()

    # ── PHASE 6: Clear pending approvals ──
    _pending_approvals.clear()

    # ── PHASE 7: Clear projection stores ──
    try:
        if _get_proj_mgr is not None:
            _pm = _get_proj_mgr()
            for _wf_id in list(_pm.get_workflow_ids()):
                try:
                    _pm.remove_workflow(_wf_id)
                except Exception:
                    pass
    except Exception:
        pass

    # ── PHASE 8: Clear bg_id_map persistence ──
    try:
        if _load_bg_id_map is not None and _deregister_bg_id is not None:
            _all_bg = _load_bg_id_map()
            for _bg_id in list(_all_bg.keys()):
                try:
                    _deregister_bg_id(_bg_id)
                except Exception:
                    pass
    except Exception:
        pass

    # ── PHASE 9: Delete disk artifacts ──
    # Active workflow files
    try:
        from system.orchestrator.persistence import ACTIVE_WORKFLOW_DIR as _aw_dir
        if os.path.exists(_aw_dir):
            for _f in os.listdir(_aw_dir):
                if _f.endswith(".json"):
                    try:
                        os.remove(os.path.join(_aw_dir, _f))
                    except Exception:
                        pass
    except Exception:
        pass

    # Checkpoint files
    try:
        from system.orchestrator.checkpoint_manager import CHECKPOINT_DIR as _cp_dir
        if os.path.exists(_cp_dir):
            for _f in os.listdir(_cp_dir):
                if _f.endswith(".json"):
                    try:
                        os.remove(os.path.join(_cp_dir, _f))
                    except Exception:
                        pass
    except Exception:
        pass

    # bg_id_map file
    try:
        from system.orchestrator.bg_id_map import _MAP_PATH as _bg_map_path
        if os.path.exists(_bg_map_path):
            try:
                os.remove(_bg_map_path)
            except Exception:
                pass
    except Exception:
        pass

    print("[RESET] runtime reset complete")

    return {
        "status": "reset_complete",
        "stopped_workflows": stopped_count,
        "evicted_workflows": evicted_count,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
