import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByText('ChatSend →WorkflowNo').click();
  await page.getByRole('textbox', { name: 'Enter instruction…' }).click();
  await page.getByRole('textbox', { name: 'Enter instruction…' }).fill('Add 100 and 50.\nMultiply the result by 3.\nDivide the result by 5.\nMultiply the result by 7.\nSubtract 20.\nDivide the result by 2.');
  await page.getByRole('button', { name: 'Send →' }).click();
  await page.getByRole('button', { name: 'Pause' }).click();
  await page.getByRole('button', { name: 'Edit step Multiply the result' }).click();
  await page.getByRole('textbox', { name: 'purpose' }).click();
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'purpose' }).fill('Multiply the result of step_3 by 10');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('heading', { name: 'Workflow', exact: true }).click();
  await page.getByRole('button', { name: 'Resume' }).click();
  // Verify workflow becomes ACTIVE after resume (upper Workflow panel)
  await expect(page.locator('.status-pill.ACTIVE, .running-indicator').first()).toBeVisible({ timeout: 15000 });
});